# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://ahmed-komsan.github.io/
baseurl: /ahmed-komsan/
title: Ahmed Komsan
author: Ahmed Komsan
description: On this blog I share my working processes, tip and tricks, tools, and problems I found along the way.
avatar: profile.jpeg
email: ahmedkomsan0@gmail.com
github: Ahmed-Komsan # username
twitter: ahmed_komsan12
linkedin: ahmed-komsan
stackoverflow: users/8940695/ahmed-komsan   #e.g: users/2735833/proton1h1
medium: ahmed.komsan2012 #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
